## Mathematics

In [13]:
import numpy as np

x = np.array([2,5,9,7])
y = np.array([3,5,6,14])
# Basic arithematic operations
print(x + 2)
print(x - 3)
print(x * 3)
print(x / 2)
print(x**2)
print(x + y)

[ 4  7 11  9]
[-1  2  6  4]
[ 6 15 27 21]
[1.  2.5 4.5 3.5]
[ 4 25 81 49]
[ 5 10 15 21]


np.int64(183)

In [11]:
np.sin(x)
np.cos(x)
np.tan(x)

array([ 0.90929743, -0.95892427,  0.41211849,  0.6569866 ])

In [14]:
a = np.array([[2,6],
              [13,19]])
b = np.array([[5,2],
              [8,1]])
np.matmul(a,b)

array([[ 58,  10],
       [217,  45]])