## Mathematics

In [13]:
import numpy as np

x = np.array([2,5,9,7])
y = np.array([3,5,6,14])
# Basic arithematic operations
print(x + 2)
print(x - 3)
print(x * 3)
print(x / 2)
print(x**2)
print(x + y)

[ 4  7 11  9]
[-1  2  6  4]
[ 6 15 27 21]
[1.  2.5 4.5 3.5]
[ 4 25 81 49]
[ 5 10 15 21]


np.int64(183)

In [11]:
np.sin(x)
np.cos(x)
np.tan(x)

array([ 0.90929743, -0.95892427,  0.41211849,  0.6569866 ])

In [14]:
a = np.array([[2,6],
              [13,19]])
b = np.array([[5,2],
              [8,1]])
np.matmul(a,b)

array([[ 58,  10],
       [217,  45]])

## Statistics

In [3]:
import numpy as np
arr1 = np.array([[3,2,1],
                 [8,9,11],
                 [11,19,23]])
print(arr1)
np.linalg.det(arr1)

[[ 3  2  1]
 [ 8  9 11]
 [11 19 23]]


np.float64(-79.00000000000007)

In [9]:
stats = np.array([[12,8,44],[10,9,3]])

np.min(stats)

np.max(stats, axis=1) #max row wise
np.max(stats, axis=0) #max column wise

np.sum(stats)

np.int64(86)

## Reorganizing Array

In [16]:
arr1 = np.array([[1,4,4],
                 [2,9,1]])
arr2 = np.reshape(arr1,(3,2))
print(arr2)

[[1 4]
 [4 2]
 [9 1]]


In [20]:
v1 = np.array([1,0,9])
v2 = np.array([[1,2,3],
               [4,5,6]])
np.vstack([v2,v1,v2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 0, 9],
       [1, 2, 3],
       [4, 5, 6]])