In [6]:
import numpy as np

b = [1,3,6]

type(b)
npArray = np.array(b)
print(npArray)
type(npArray)
np.dtype

[1 3 6]


numpy.dtype

In [14]:
a = np.array([[2,3,5,6,6],[4,5,7,8,9]], dtype=np.int32)
print(a)
print("Dimension:",a.ndim)
print("Shape of Array (Rows, Column)",a.shape)
print("Item Size:",a.itemsize)
print("Total number of Bytes:",a.nbytes)


[[2 3 5 6 6]
 [4 5 7 8 9]]
Dimension: 2
Shape of Array (Rows, Column) (2, 5)
Item Size: 4
Total number of Bytes: 40


In [22]:
x = np.array([[2,3,4,5,6],[7,8,3,2,8]])
print(x)
print("Accessing Element of Array:", x[1][4])
print("Accessing Element of Array:", x[1,3])
print("Accessing Element of Array:", x[1,3])
print("Get Specific Row:", x[1,:])
print("Get Specific Column:", x[:,2])
x[0,2] = 16
print(x)



[[2 3 4 5 6]
 [7 8 3 2 8]]
Accessing Element of Array: 8
Accessing Element of Array: 2
Accessing Element of Array: 2
Get Specific Row: [7 8 3 2 8]
Get Specific Column: [4 3]
[[ 2  3 16  5  6]
 [ 7  8  3  2  8]]


In [44]:
c = np.array([[[3,6],[10,11]],[[8,9],[13,18]]])
print(c)
print("Shape of Array:", c.shape)
print("Dimension of Array:", c.ndim)
print("1st layer , 2nd row, 2nd column:", c[0][1][1])
print("1st layer , 2nd row, 2nd column:", c[0,0,1])
print("Accessing:", c[:,0,:])
print("Accessing:", c[:,1,:])
print("Accessing:", c[:,:,0])
print("Accessing:", c[:,:,1])

print("Replacing Elements in an Array")

c[:,0,:] = [[4,8],[6,12]]

print(c)

c[:,:,1] = [[5,10],[7,14]]

print(c)


[[[ 3  6]
  [10 11]]

 [[ 8  9]
  [13 18]]]
Shape of Array: (2, 2, 2)
Dimension of Array: 3
1st layer , 2nd row, 2nd column: 11
1st layer , 2nd row, 2nd column: 6
Accessing: [[3 6]
 [8 9]]
Accessing: [[10 11]
 [13 18]]
Accessing: [[ 3 10]
 [ 8 13]]
Accessing: [[ 6 11]
 [ 9 18]]
Replacing Elements in an Array
[[[ 4  8]
  [10 11]]

 [[ 6 12]
  [13 18]]]
[[[ 4  5]
  [10 10]]

 [[ 6  7]
  [13 14]]]


##INITIALIZING ARRAYS


In [9]:
import numpy as np

#create arrays of zero
np.zeros((3,2))

x = [[78,98,64],
     [65,34,89]]

# create an array of ones
np.ones((4,2,2), dtype='int32')

# create an array of any number
np.full((3,3), 78) 

#create a copy of array with any number
np.full_like(x, 5)


array([[5, 5, 5],
       [5, 5, 5]])

In [13]:
#generate a random array of size 3x3 
np.random.rand(3,3)

#generate a random array of size 3x3 from range 1 to 99
np.random.randint(1,99, size=(3,3))

#creates an identity matrix of size 6x6
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [18]:
# repeat an array
arr = np.array([[2,4],
               [4,2]])
r1 = np.repeat(arr,2,axis=0)
print(r1)

[[2 4]
 [2 4]
 [4 2]
 [4 2]]


In [26]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,2] = 89
print(z)

output[1:-1, 1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[ 0.  0.  0.]
 [ 0.  0. 89.]
 [ 0.  0.  0.]]
[[ 1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  0.  0. 89.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.]]


In [2]:
import numpy as np
a = np.array([0,3,1])
b = a.copy()
b[0] = 100
print(b)

[100   3   1]
